const MainPageActionTypes = {
  FACE_RECOGNITION_START: 'FACE_RECOGNITION_START',
  FACE_RECOGNITION_SUCCESS: 'FACE_RECOGNITION_SUCCESS',
  FACE_RECOGNITION_FAILURE: 'FACE_RECOGNITION_FAILURE',
}

export default MainPageActionTypes
