const ProfileActionTypes = {
  GET_PROFILE_START: 'GET_PROFILE_START',
  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  PROFILE_OPERATION_SUCCESS: 'PROFILE_OPERATION_SUCCESS',
  PROFILE_OPERATION_FAILURE: 'PROFILE_OPERATION_FAILURE',
}

export default ProfileActionTypes
