const MainPageActionTypes = {
  FACE_RECOGNITION_START: 'FACE_RECOGNITION_START',
  FACE_RECOGNITION_SUCCESS: 'FACE_RECOGNITION_SUCCESS',
  FACE_RECOGNITION_FAILURE: 'FACE_RECOGNITION_FAILURE',
  CLEAR_FACES_DATA: 'CLEAR_FACES_DATA',
}

export default MainPageActionTypes
