const UserActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  USER_OPERATION_SUCCESS: 'USER_OPERATION_SUCCESS',
  USER_OPERATION_FAILURE: 'USER_OPERATION_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP_START: 'SIGN_UP_START',
  UPDATE_USER_START: 'UPDATE_USER_START',
}

export default UserActionTypes
