const UserActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  USER_OPERATION_SUCCESS: 'USER_OPERATION_SUCCESS',
  USER_OPERATION_FAILURE: 'USER_OPERATION_FAILURE',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP_START: 'SIGN_UP_START',
  USER_UPDATE_START: 'USER_UPDATE_START',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
}

export default UserActionTypes
